[package]
name = "hello_cargo_h"
version = "0.1.0"
edition = "2021"
description = "测试发布一个cargo包"
license = "MIT"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
